module.exports.adjectifs = [
    'magnifiques',
    'anciennes',
    'nouvelles',
    'dingues',
    'sombres',
    'affreux',
    'parfaits',
    'bonnes',
    'super',
    'remarquables',
    'excellentes',
    'puantes',
    'ignorés',
    'bleus',
    'mouillés',
    'sèches',
    'savoureux',
    'dorées'
]

module.exports.sujets = [
    'Jeux vidéo',
    'Émissions de télévision',
    'Films',
    'Séances d\'entraînement',
    'Recettes',
    'Ordinateurs',
    'Téléphones cellulaires',
    'Services de diffusion',
    'Restaurants',
    'Bureaux',
    'Voitures',
    'Chansons',
    'Pommes',
    'Boissons',
    'Pantalons',
    'Gants',
    'Bijoux',
    'Chemises',
    'Bâtiments',
    'Points de vue',
    'Pépites'
]